DEVICE_NAME = "coder-buddy"

SERVO_PIN = 14
SERVO_NEUTRAL_ANGLE = 90
SERVO_MIN_ANGLE = 80
SERVO_MAX_ANGLE = 100
SERVO_STEP_MS = 25
SERVO_HZ = 50
SERVO_MIN_US = 500
SERVO_MAX_US = 2500

RGB_R_PIN = 4
RGB_G_PIN = 5
RGB_B_PIN = 6
RGB_COMMON_CATHODE = True
RGB_PWM_HZ = 1000

BUTTON_PIN = 7
BUTTON_ACTIVE_LOW = True
BUTTON_PULL_UP = True

I2S_ID = 0
I2S_SCK_PIN = 17
I2S_WS_PIN = 18
I2S_SD_PIN = 16
AMP_ENABLE_PIN = 15
AMP_ENABLE_ACTIVE_HIGH = True

AUDIO_DIR = "/audio"
DEFAULT_TRACK = "approve_soft.wav"
MAX_LEVEL = 10
HTTP_PORT = 80
